#pragma once

#include "NativeGameplayTags.h"

namespace LG::SurvivalTags
{
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Room_Type_Normal);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Room_Type_Monster);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Room_Type_HighResource);

	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Resource);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Enemy);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Workbench);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_TeamTerminal);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_RespawnBase);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_PlayerStart);

	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Ammo);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Food);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Water);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Medical);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material);
	LEGOGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_RespawnEnergy);
}
